version: '3.8'

services:
  web:
    build: ./
    container_name: web
    command: python ./src/manage.py runserver 0:8000
    restart: always
    volumes:
      - .:/usr/src/app/
    ports:
      - "${WSGI_PORT}:${WSGI_PORT}"
    env_file:
      - ./.env
    depends_on:
      - postgresql
  postgresql:
    image: postgres:13.0-alpine
    container_name: postgresql
    hostname: ${POSTGRES_HOST}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env

volumes:
  postgres_data: {}