# Generated by Django 3.1.2 on 2020-10-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='final_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
