# Generated by Django 3.1.2 on 2020-10-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_fill_users'),
        ('transaction', '0003_auto_20201020_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_transactions', to='account.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Success'), (0, 'Fail')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_transactions', to='account.wallet'),
        ),
    ]
