# Generated by Django 3.1.2 on 2020-10-20 12:58

import bitcoin.main
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False)),
                ('public_key', models.CharField(editable=False, max_length=130)),
                ('private_key', models.CharField(default=bitcoin.main.random_key, editable=False, max_length=128)),
                ('balance', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
