# Generated by Django 3.1.2 on 2020-10-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_amount', models.BigIntegerField()),
                ('final_amount', models.BigIntegerField()),
                ('source_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_transactions', to='account.wallet')),
                ('target_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_transactions', to='account.wallet')),
            ],
        ),
    ]
