# Generated by Django 3.1.2 on 2020-10-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Success'), (0, 'Fail')], default=0),
        ),
    ]
